feat(dynamic-faceting): add guide using QR in RIS
algolia/instantsearch-labs pull request #8
Opened 2018-08-07 12:39 UTC by Haroenv

2018-08-07 12:41 UTC, Haroenv commented on dynamic-faceting-qr/react-instantsearch/README.md
> +[![screenshot](https://codesandbox.io/api/v1/sandboxes/2x0pvzvr8p/screenshot.png)](https://codesandbox.io/s/github/algolia/dynamic-faceting-guide)
still need to change these links once merged

2018-08-07 17:56 UTC, samouss commented on dynamic-faceting-qr/react-instantsearch/README.md
> +      { attribute: 'category', widgetName: 'RefinementList' },
Not only:

```js
// From the guide
categories, type, brand, price

// From the code
categories, type, manufacturer, salePrice
```

2018-08-08 06:55 UTC, Haroenv commented on dynamic-faceting-qr/react-instantsearch/README.md
> +```jsx
funnily this is only in the diff, but changed it anyway

2018-08-08 09:39 UTC, mthuret requested changes
Hey @Haroenv, thanks for this PR! 
Can you modify the Readme to try to keep the same format as the other labs? See https://github.com/algolia/instantsearch-labs/tree/master/autocomplete%2BdelayedHits/instantsearch.js or https://github.com/algolia/instantsearch-labs/tree/master/instantsearch-relevance-widget/instantsearch.js 

Thanks in advance!

2020-10-09 07:27 UTC, closed without merging